spring:
  profiles:
    group:
      local : "local"
      dev : "dev"
      prod : "prod"

---

spring:
  # Unnecessary and having issues:
  #   If profile is set, then settings sibling with spring will be set lazily.
  #   It could happens unexpected bugs by lazy setting.
  # config:
  #  activate:
  #    on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
  type-handlers-package: kr.texturized.muus.infrastructure.mapper.handler.type

server:
  port: 10023

cloud:
  credentials:
    access-key: none
    secret-key: none
  storage:
    endpoint: none
    region:
      static: none
    bucket-name: none
