spring:
  profiles:
    group:
      local : "common,local"
      dev : "common,dev"
      prod : "common,prod"

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 10023

