spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:muus-local
    username: redgem92
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  devtools:
    add-properties: true
cloud:
  credentials:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
  storage:
    endpoint: https://kr.object.ncloudstorage.com
    region:
      static: kr-standard
    bucket-name: ${NCP_OBJECT_STORAGE_BUCKET_NAME}
logging:
  level:
    kr.texturized.muus: debug

