spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:muus-test;MODE=mysql;
    username: redgem92
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  devtools:
    add-properties: true

cloud:
  credentials:
    access-key: ${CLOUD_ACCESS_KEY}
    secret-key: ${CLOUD_SECRET_KEY}
  storage:
    endpoint: ${STORAGE_END_POINT}
    region:
      static: ${STORAGE_REGION}
    bucket-name: ${STORAGE_BUCKET_NAME}

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace

