spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/muus-test
    username: redgem92
  jpa:
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create-drop

  devtools:
    add-properties: true
logging:
  level:
    com.texturized.muus: debug



