name: CI/CD

on:
  push:
    branches:
      - develop
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test
        run: ./gradlew test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build
        run: ./gradlew build -x test -Pprofile=prod

  Complete:
    runs-on: ubuntu-latest
    needs:
      - Test
      - Build
    steps:
      - name: Run
        run: echo "complete"
      
    
